### ISSUE TITLE
New Plugins

### ISSUE THREAD

**Issue by cuddlycheetah** [madmatt/streamdeck-plugins#10]
https://github.com/cuddlycheetah/sch.umann.it.obs.replay
 and
https://github.com/cuddlycheetah/sch.umann.it.steam.launch

**Comment by BarRaider** [comment]
Hi,

Where is the source code for the plugins located?

**Comment by cuddlycheetah** [comment]
https://github.com/cuddlycheetah/sch.umann.it.obs.replay
https://github.com/cuddlycheetah/sch.umann.it.steam.launch

Von: BarRaider
Gesendet: Mittwoch, 26. Juni 2019 15:50
An: madmatt/streamdeck-plugins
Cc: Cuddly Cheetah; Author
Betreff: Re: [madmatt/streamdeck-plugins] New Plugins (#10)

Hi,
Where is the source code for the plugins located?

**Comment by BarRaider** [comment]
Thanks, will add them today

**Comment by BarRaider** [comment]
I added them to the list. I also opened an issue on the Steam Launcher, I'm not sure you actually need to go to your website to launch them, and it also raises some privacy concerns
