### ISSUE TITLE
Do you have a plan to support python ?

### ISSUE THREAD

**Issue by coderge** [madmatt/streamdeck-plugins#21]
I saw the SDK support Javascript, C++, Object-C now, but they are unfriendly to executing a shell.
If you can support Python, I think it will have much more possibilities.

**Comment by BarRaider** [comment]
Hi,

This site is not officially affiliated with Elgato, so this is probably a question to ask them directly.
Regardless, there are additional packages for additional languages, like C#:
https://www.nuget.org/packages/StreamDeck-Tools/
