### ISSUE TITLE
New Plugin

### ISSUE THREAD

**Issue by ripnet** [madmatt/streamdeck-plugins#36]
1. Plugin name: Hubitat Integration
2. Plugin description: Use Stream Deck to control your [Hubitat](https://hubitat.com/) devices.
3. Supports Windows (Yes/No): Yes
4. Supports Mac (Yes/No): Yes
5. Author name + Homepage URL: Tom Young + https://github.com/ripnet
6. Plugin download link: https://github.com/ripnet/streamdeck-hubitat

**Comment by ripnet** [comment]
friendly bump!

**Comment by madmatt** [comment]
This was resolved back on 30 Jan, thanks for the bump (and thanks @BarRaider for merging it).
